FROM golang:1.23 AS build
WORKDIR /src
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 go build -o /out/metering ./cmd/metering

FROM gcr.io/distroless/static-debian12
COPY --from=build /out/metering /metering
ENTRYPOINT ["/metering"]
